# Generated by Django 2.1.2 on 2018-10-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djangoboard',
            name='content',
        ),
        migrations.RemoveField(
            model_name='djangoboard',
            name='title',
        ),
        migrations.RemoveField(
            model_name='djangoboard',
            name='user_name',
        ),
        migrations.AddField(
            model_name='djangoboard',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='djangoboard',
            name='hits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='djangoboard',
            name='mail',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='djangoboard',
            name='memo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='djangoboard',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='djangoboard',
            name='subject',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='djangoboard',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
