# Generated by Django 2.1.2 on 2018-10-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postboard', '0002_auto_20181031_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoboard',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
